version: '2.1'
services:

    gatsby-deploy:
        build:
            context: ./services/gatsby-deploy
            dockerfile: Dockerfile.dev
        networks:
            - development
        ports:
            - ${HUMBLE_PORT:-8080}:8080
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL:-info}
            JWT_SECRET: ${JWT_SECRET:-gatsby-deploy}
            GITHUB_TOKEN: ${GITHUB_TOKEN}
        volumes:
            - ${HUMBLE_DATA}:/tmp/gatsby-deploy
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start" ]
    
networks:
    development:
